# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/",
        "doc_host": "",
        "git_url": "https://github.com/majorgilles/build-llms-from-scratch-companion",
        "lib_path": "build_llms_from_scratch_companion",
    },
    "syms": {
        "build_llms_from_scratch_companion.attention": {
            "build_llms_from_scratch_companion.attention.MultiHeadAttention": (
                "03-coding-attention-mechanisms.html#multiheadattention",
                "build_llms_from_scratch_companion/attention.py",
            ),
            "build_llms_from_scratch_companion.attention.MultiHeadAttention.__init__": (
                "03-coding-attention-mechanisms.html#multiheadattention.__init__",
                "build_llms_from_scratch_companion/attention.py",
            ),
            "build_llms_from_scratch_companion.attention.MultiHeadAttention.forward": (
                "03-coding-attention-mechanisms.html#multiheadattention.forward",
                "build_llms_from_scratch_companion/attention.py",
            ),
        }
    },
}
