# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/",
        "doc_host": "",
        "git_url": "https://github.com/majorgilles/build-llms-from-scratch-companion",
        "lib_path": "build_llms_from_scratch_companion",
    },
    "syms": {
        "build_llms_from_scratch_companion.attention": {
            "build_llms_from_scratch_companion.attention.MultiHeadAttention": (
                "03-coding-attention-mechanisms.html#multiheadattention",
                "build_llms_from_scratch_companion/attention.py",
            ),
            "build_llms_from_scratch_companion.attention.MultiHeadAttention.__init__": (
                "03-coding-attention-mechanisms.html#multiheadattention.__init__",
                "build_llms_from_scratch_companion/attention.py",
            ),
            "build_llms_from_scratch_companion.attention.MultiHeadAttention.forward": (
                "03-coding-attention-mechanisms.html#multiheadattention.forward",
                "build_llms_from_scratch_companion/attention.py",
            ),
        },
        "build_llms_from_scratch_companion.data": {
            "build_llms_from_scratch_companion.data.GPTDatasetV1": (
                "02-working-with-text-data.html#gptdatasetv1",
                "build_llms_from_scratch_companion/data.py",
            ),
            "build_llms_from_scratch_companion.data.GPTDatasetV1.__getitem__": (
                "02-working-with-text-data.html#gptdatasetv1.__getitem__",
                "build_llms_from_scratch_companion/data.py",
            ),
            "build_llms_from_scratch_companion.data.GPTDatasetV1.__init__": (
                "02-working-with-text-data.html#gptdatasetv1.__init__",
                "build_llms_from_scratch_companion/data.py",
            ),
            "build_llms_from_scratch_companion.data.GPTDatasetV1.__len__": (
                "02-working-with-text-data.html#gptdatasetv1.__len__",
                "build_llms_from_scratch_companion/data.py",
            ),
            "build_llms_from_scratch_companion.data.create_dataloader_v1": (
                "02-working-with-text-data.html#create_dataloader_v1",
                "build_llms_from_scratch_companion/data.py",
            ),
        },
        "build_llms_from_scratch_companion.generation": {
            "build_llms_from_scratch_companion.generation.generate_text_simple": (
                "04a-generation.html#generate_text_simple",
                "build_llms_from_scratch_companion/generation.py",
            )
        },
        "build_llms_from_scratch_companion.model": {
            "build_llms_from_scratch_companion.model.FeedForward": (
                "04-implementing-a-gpt-model.html#feedforward",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.FeedForward.__init__": (
                "04-implementing-a-gpt-model.html#feedforward.__init__",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.FeedForward.forward": (
                "04-implementing-a-gpt-model.html#feedforward.forward",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GELU": (
                "04-implementing-a-gpt-model.html#gelu",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GELU.__init__": (
                "04-implementing-a-gpt-model.html#gelu.__init__",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GELU.forward": (
                "04-implementing-a-gpt-model.html#gelu.forward",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GPTConfig": (
                "04-implementing-a-gpt-model.html#gptconfig",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GPTConfig.head_dim": (
                "04-implementing-a-gpt-model.html#gptconfig.head_dim",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GPTConfig.validate_attention_dimensions": (
                "04-implementing-a-gpt-model.html#gptconfig.validate_attention_dimensions",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GPTModel": (
                "04-implementing-a-gpt-model.html#gptmodel",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GPTModel.__init__": (
                "04-implementing-a-gpt-model.html#gptmodel.__init__",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.GPTModel.forward": (
                "04-implementing-a-gpt-model.html#gptmodel.forward",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.LayerNorm": (
                "04-implementing-a-gpt-model.html#layernorm",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.LayerNorm.__init__": (
                "04-implementing-a-gpt-model.html#layernorm.__init__",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.LayerNorm.forward": (
                "04-implementing-a-gpt-model.html#layernorm.forward",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.TransformerBlock": (
                "04-implementing-a-gpt-model.html#transformerblock",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.TransformerBlock.__init__": (
                "04-implementing-a-gpt-model.html#transformerblock.__init__",
                "build_llms_from_scratch_companion/model.py",
            ),
            "build_llms_from_scratch_companion.model.TransformerBlock.forward": (
                "04-implementing-a-gpt-model.html#transformerblock.forward",
                "build_llms_from_scratch_companion/model.py",
            ),
        },
        "build_llms_from_scratch_companion.training": {
            "build_llms_from_scratch_companion.training.assign": (
                "05-pretraining-on-unlabeled-data.html#assign",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.calc_loss_batch": (
                "05-pretraining-on-unlabeled-data.html#calc_loss_batch",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.calc_loss_loader": (
                "05-pretraining-on-unlabeled-data.html#calc_loss_loader",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.evaluate_model": (
                "05-pretraining-on-unlabeled-data.html#evaluate_model",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.generate_and_print_sample": (
                "05-pretraining-on-unlabeled-data.html#generate_and_print_sample",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.load_weights_into_gpt": (
                "05-pretraining-on-unlabeled-data.html#load_weights_into_gpt",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.plot_losses": (
                "05-pretraining-on-unlabeled-data.html#plot_losses",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.text_to_token_ids": (
                "05-pretraining-on-unlabeled-data.html#text_to_token_ids",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.token_ids_to_text": (
                "05-pretraining-on-unlabeled-data.html#token_ids_to_text",
                "build_llms_from_scratch_companion/training.py",
            ),
            "build_llms_from_scratch_companion.training.train_model_simple": (
                "05-pretraining-on-unlabeled-data.html#train_model_simple",
                "build_llms_from_scratch_companion/training.py",
            ),
        },
    },
}
