# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/03-coding-attention-mechanisms.ipynb.

# %% auto #0
__all__ = ['MultiHeadAttention']

# %% ../notebooks/03-coding-attention-mechanisms.ipynb #nbdev-export-imports
import torch
from torch import nn

# %% ../notebooks/03-coding-attention-mechanisms.ipynb #b8791648b2c4dc65
class MultiHeadAttention(nn.Module):
    """Compute causal multi-head attention with configurable input/output widths.

    This educational class maps `(B, T, d_in)` to `(B, T, d_out)`. To match
    the Transformer paper's residual-stream contract, construct it with
    `d_in == d_out == d_model`.
    """

    def __init__(
        self,
        d_in: int,
        d_out: int,
        context_length: int,
        dropout: float,
        num_heads: int,
        qkv_bias: bool = False,
    ) -> None:
        """Initialize combined QKV projections, causal mask, and output layer."""
        super().__init__()
        assert d_out % num_heads == 0, "d_out must be divisible by num_heads"

        # d_out is the total width after all heads are concatenated.
        self.d_out = d_out
        self.num_heads = num_heads
        # Each head receives an equal slice of the projected features.
        self.head_dim = d_out // num_heads
        # Each projection computes every head in one linear operation.
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        # This educational version preserves d_out, not necessarily d_in.
        # In the paper, W_O maps concatenated heads back to d_model.
        self.out_proj = nn.Linear(d_out, d_out)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            # mask: (context_length, context_length)
            "mask",
            torch.triu(
                torch.ones(context_length, context_length),
                diagonal=1,
            ),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Map `(batch, tokens, d_in)` to `(batch, tokens, d_out)`.

        Residual addition requires `d_out == d_in`; GPT-style usage sets both
        dimensions to `d_model`.
        """
        # x: (batch, num_tokens, d_in)
        b, num_tokens, d_in = x.shape

        # Combined projections: (batch, num_tokens, d_out)
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        # Split d_out into heads:
        # (batch, num_tokens, d_out)
        # -> (batch, num_tokens, num_heads, head_dim)
        keys = keys.view(b, num_tokens, self.num_heads, self.head_dim)
        values = values.view(b, num_tokens, self.num_heads, self.head_dim)
        queries = queries.view(b, num_tokens, self.num_heads, self.head_dim)

        # Move heads before tokens for parallel attention:
        # (batch, num_heads, num_tokens, head_dim)
        keys = keys.transpose(1, 2)
        queries = queries.transpose(1, 2)
        values = values.transpose(1, 2)

        # keys.transpose(2, 3): (batch, num_heads, head_dim, num_tokens)
        # attn_scores: (batch, num_heads, num_tokens, num_tokens)
        attn_scores = queries @ keys.transpose(2, 3)

        # mask_bool: (num_tokens, num_tokens), broadcast over batch and heads
        mask_bool = self.mask.bool()[:num_tokens, :num_tokens]
        # attn_scores remains: (batch, num_heads, num_tokens, num_tokens)
        attn_scores.masked_fill_(mask_bool, -torch.inf)

        # attn_weights: (batch, num_heads, num_tokens, num_tokens)
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1] ** 0.5,
            dim=-1,
        )
        attn_weights = self.dropout(attn_weights)

        # Weighted values: (batch, num_heads, num_tokens, head_dim)
        # After transpose: (batch, num_tokens, num_heads, head_dim)
        context_vec = (attn_weights @ values).transpose(1, 2)

        # Merge heads: (batch, num_tokens, num_heads * head_dim)
        # Since num_heads * head_dim == d_out: (batch, num_tokens, d_out)
        context_vec = context_vec.contiguous().view(b, num_tokens, self.d_out)
        # out_proj preserves: (batch, num_tokens, d_out)
        context_vec = self.out_proj(context_vec)
        return context_vec
