# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/02-working-with-text-data.ipynb.

# %% auto #0
__all__ = ["GPTDatasetV1", "create_dataloader_v1"]

# %% ../notebooks/02-working-with-text-data.ipynb #ec39b49cace3bd7e
import tiktoken
import torch
from torch.utils.data import DataLoader, Dataset


class GPTDatasetV1(Dataset):
    """Create overlapping input-target token windows from a text corpus.

    Each dataset item contains two tensors shaped `(max_length,)`. A data
    loader stacks those items into `(batch_size, max_length)` batches.
    """

    def __init__(
        self,
        txt: str,
        tokenizer: tiktoken.Encoding,
        max_length: int,
        stride: int,
    ) -> None:
        """Tokenize text and materialize shifted windows as tensors.

        Args:
            txt: Complete text corpus used to create token windows.
            tokenizer: Tokenizer that converts the text into token IDs.
            max_length: Number of token IDs in each input and target window.
            stride: Number of token positions between consecutive window starts.
        """
        # Each list item will be a one-dimensional tensor shaped (max_length,).
        # Empty collections need annotations because their item type is not inferable.
        self.input_ids: list[torch.Tensor] = []
        self.target_ids: list[torch.Tensor] = []

        # token_ids: (num_tokens,) represented as a Python list of integers
        token_ids = tokenizer.encode(txt)

        # Stride is the range step: windows start at 0, stride, 2 * stride, and so on.
        for i in range(0, len(token_ids) - max_length, stride):
            # input_chunk: (max_length,) represented as a Python list
            input_chunk = token_ids[i : i + max_length]
            # target_chunk: (max_length,), shifted one token beyond input_chunk
            target_chunk = token_ids[i + 1 : i + max_length + 1]
            # Each conversion stores one tensor shaped (max_length,).
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self) -> int:
        """Return the number of available input-target windows.

        Returns:
            Number of input-target window pairs in the dataset.
        """
        return len(self.input_ids)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        """Return one input window and its shifted target window.

        Args:
            idx: Zero-based index of the window pair to retrieve.

        Returns:
            Input and target token IDs, each shaped `(max_length,)`.
        """
        # input_ids and target_ids: (max_length,)
        return self.input_ids[idx], self.target_ids[idx]


# %% ../notebooks/02-working-with-text-data.ipynb #2602395bc437d4e8
def create_dataloader_v1(
    txt: str,
    batch_size: int = 4,
    max_length: int = 256,
    stride: int = 128,
    shuffle: bool = True,
    drop_last: bool = True,
    num_workers: int = 0,
) -> DataLoader[tuple[torch.Tensor, torch.Tensor]]:
    """Build a data loader of shifted token windows from raw text.

    Args:
        txt: Complete text corpus used to create token windows.
        batch_size: Number of independent windows in each batch.
        max_length: Number of token IDs in each input and target window.
        stride: Number of token positions between consecutive window starts.
        shuffle: Whether to randomize window order before each iteration.
        drop_last: Whether to discard a final batch smaller than `batch_size`.
        num_workers: Number of subprocesses used to load batches.

    Returns:
        Data loader yielding `(inputs, targets)` tensors, each shaped
        `(batch_size, max_length)` for complete batches.
    """
    tokenizer = tiktoken.get_encoding("gpt2")
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # DataLoader handles batching, optional shuffling, and worker processes.
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
    )
    return dataloader
