# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/04a-generation.ipynb.

# %% auto #0
__all__ = ["generate_text_simple", "generate"]

# %% ../notebooks/04a-generation.ipynb #generation-imports
import torch

from .model import GPTModel


# %% ../notebooks/04a-generation.ipynb #generate-text-simple
def generate_text_simple(
    model: GPTModel,
    idx: torch.Tensor,
    max_new_tokens: int,
    context_size: int,
) -> torch.Tensor:
    """Append greedily selected token IDs to a batch of input token IDs.

    Args:
        model: GPT model used to produce next-token logits.
        idx: Input token IDs shaped `(batch_size, num_tokens)`.
        max_new_tokens: Number of token IDs to generate and append.
        context_size: Maximum number of recent token IDs supplied to the model.

    Returns:
        Token IDs shaped
        `(batch_size, num_tokens + max_new_tokens)`.
    """
    for _ in range(max_new_tokens):
        # idx: (batch_size, num_tokens)
        # idx_cond: (batch_size, min(num_tokens, context_size))
        idx_cond = idx[:, -context_size:]
        # Generation is inference-only, so no backward graph is required.
        with torch.no_grad():
            # logits: (batch_size, min(num_tokens, context_size), vocab_size)
            logits = model(idx_cond)

        # Keep the next-token logits from the final input position only.
        # logits: (batch_size, vocab_size)
        logits = logits[:, -1, :]
        # probas: (batch_size, vocab_size)
        probas = torch.softmax(logits, dim=-1)
        # idx_next: (batch_size, 1)
        idx_next = torch.argmax(probas, dim=-1, keepdim=True)
        # idx: (batch_size, num_tokens + 1)
        idx = torch.cat((idx, idx_next), dim=1)

    return idx


# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #1b9ab9053b20fcb0
def generate(
    model: GPTModel,
    idx: torch.Tensor,
    max_new_tokens: int,
    context_size: int,
    temperature: float = 0.0,
    top_k: int | None = None,
    eos_id: int | None = None,
) -> torch.Tensor:
    """Generate token IDs with optional top-k and temperature sampling.

    Args:
        model: GPT model used to calculate next-token logits.
        idx: Input token IDs shaped `(batch_size, num_tokens)`.
        max_new_tokens: Maximum number of token IDs appended to `idx`.
        context_size: Maximum recent token IDs supplied to the model; maps to
            the configured `context_length`.
        temperature: Positive sampling scale, or `0.0` for greedy decoding.
        top_k: Highest-logit candidates retained, or `None` for all candidates.
        eos_id: Optional token ID that stops generation when selected by every
            sequence in the batch.

    Returns:
        Token IDs shaped up to
        `(batch_size, num_tokens + max_new_tokens)`.
    """
    for _ in range(max_new_tokens):
        # idx_cond: (batch_size, min(num_tokens, context_size))
        idx_cond = idx[:, -context_size:]
        with torch.no_grad():
            # logits: (batch_size, min(num_tokens, context_size), vocab_size)
            logits = model(idx_cond)
        # Keep only the final position: (batch_size, vocab_size)
        logits = logits[:, -1, :]

        if top_k is not None:
            # top_logits: (batch_size, top_k)
            top_logits, _ = torch.topk(logits, top_k)
            # min_top_k_logits: (batch_size, 1), broadcast across vocab_size
            min_top_k_logits = top_logits[:, -1:]
            # Excluded vocabulary logits become -inf and receive probability 0.
            logits = logits.masked_fill(logits < min_top_k_logits, -torch.inf)

        if temperature > 0.0:
            # probas: (batch_size, vocab_size)
            probas = torch.softmax(logits / temperature, dim=-1)
            # Sample one ID per sequence: (batch_size, 1)
            idx_next = torch.multinomial(probas, num_samples=1)
        else:
            # Greedily select one ID per sequence: (batch_size, 1)
            idx_next = torch.argmax(logits, dim=-1, keepdim=True)

        # Stop only when an eos_id is configured and every sequence selects it.
        if eos_id is not None and torch.all(idx_next == eos_id):
            break
        # idx: (batch_size, num_tokens + 1)
        idx = torch.cat((idx, idx_next), dim=1)
    return idx
