# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/04-implementing-a-gpt-model.ipynb.

# %% auto #0
__all__ = ['GPT_CONFIG_124M', 'GPTConfig', 'LayerNorm', 'GELU', 'FeedForward', 'TransformerBlock', 'GPTModel']

# %% ../notebooks/04-implementing-a-gpt-model.ipynb #nbdev-export-model-imports
from typing import Self

import torch
from pydantic import BaseModel, ConfigDict, Field, model_validator
from torch import nn

from .attention import MultiHeadAttention

# %% ../notebooks/04-implementing-a-gpt-model.ipynb #91741fecc8c044b3
class GPTConfig(BaseModel):
    """Validated architecture settings for a GPT-style language model."""

    # Configuration objects behave like immutable architecture specifications.
    model_config = ConfigDict(frozen=True)

    vocab_size: int = Field(gt=0, description="Number of tokenizer vocabulary entries")
    context_length: int = Field(gt=0, description="Maximum supported token sequence length")
    emb_dim: int = Field(
        gt=0, description="Token embedding and model dimension, also called d_model"
    )
    num_heads: int = Field(gt=0, description="Number of parallel attention heads")
    num_layers: int = Field(gt=0, description="Number of Transformer blocks")
    dropout_rate: float = Field(ge=0.0, lt=1.0, description="Dropout probability")
    qkv_bias: bool = Field(description="Whether QKV projections include bias terms")

    @model_validator(mode="after")
    def validate_attention_dimensions(self) -> Self:
        """Require every attention head to receive an equal feature width."""
        if self.emb_dim % self.num_heads != 0:
            raise ValueError("emb_dim must be divisible by num_heads")
        return self

    @property
    def head_dim(self) -> int:
        """Return the query, key, and value width assigned to one head."""
        return self.emb_dim // self.num_heads


# GPT-2 small / 124M uses a model dimension of 768 and 12 attention heads.
GPT_CONFIG_124M = GPTConfig(
    vocab_size=50257,
    context_length=1024,
    emb_dim=768,
    num_heads=12,
    num_layers=12,
    dropout_rate=0.1,
    qkv_bias=False,
)

# %% ../notebooks/04-implementing-a-gpt-model.ipynb #c08013d559196d53
class LayerNorm(nn.Module):
    """Normalize each token across its embedding features."""

    def __init__(self, emb_dim: int) -> None:
        """Create learnable scale and shift vectors of width `emb_dim`."""
        super().__init__()
        self.eps = 1e-5
        # scale and shift: (emb_dim,), broadcast across batch and tokens
        self.scale = nn.Parameter(torch.ones(emb_dim))
        self.shift = nn.Parameter(torch.zeros(emb_dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Normalize `(batch_size, num_tokens, emb_dim)` without changing shape."""
        # mean and var: (batch_size, num_tokens, 1)
        mean = x.mean(dim=-1, keepdim=True)
        # LayerNorm uses population variance rather than the unbiased estimate.
        var = x.var(dim=-1, keepdim=True, unbiased=False)
        # norm_x: (batch_size, num_tokens, emb_dim)
        norm_x = (x - mean) / torch.sqrt(var + self.eps)
        # Learned affine parameters broadcast across batch and token dimensions.
        return self.scale * norm_x + self.shift

# %% ../notebooks/04-implementing-a-gpt-model.ipynb #7e138ab244470c2e
class GELU(nn.Module):
    """Apply the smooth Gaussian Error Linear Unit approximation."""

    def __init__(self) -> None:
        """Initialize a parameter-free activation module."""
        super().__init__()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Apply GELU element-wise without changing the input shape."""
        # The tanh approximation used by GPT preserves every tensor dimension.
        return (
            0.5
            * x
            * (
                1
                + torch.tanh(
                    torch.sqrt(torch.tensor(2.0 / torch.pi)) * (x + 0.044715 * torch.pow(x, 3))
                )
            )
        )

# %% ../notebooks/04-implementing-a-gpt-model.ipynb #6695727aafdad6de
class FeedForward(nn.Module):
    """Apply GPT's position-wise two-layer feed-forward network."""

    def __init__(self, cfg: GPTConfig) -> None:
        """Expand token features fourfold, apply GELU, and project them back."""
        super().__init__()
        self.layers = nn.Sequential(
            # (batch_size, num_tokens, emb_dim)
            # -> (batch_size, num_tokens, 4 * emb_dim)
            nn.Linear(cfg.emb_dim, 4 * cfg.emb_dim),
            # GELU preserves (batch_size, num_tokens, 4 * emb_dim).
            GELU(),
            # -> (batch_size, num_tokens, emb_dim)
            nn.Linear(4 * cfg.emb_dim, cfg.emb_dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Transform each token independently without changing tensor shape."""
        # x and output: (batch_size, num_tokens, emb_dim)
        return self.layers(x)

# %% ../notebooks/04-implementing-a-gpt-model.ipynb #838d892758e9f58
class TransformerBlock(nn.Module):
    """Apply one pre-normalization GPT Transformer block."""

    def __init__(self, cfg: GPTConfig) -> None:
        """Initialize attention, feed-forward, normalization, and dropout layers."""
        super().__init__()
        # d_in == d_out == emb_dim preserves the shortcut-addition contract.
        self.att = MultiHeadAttention(
            d_in=cfg.emb_dim,
            d_out=cfg.emb_dim,
            context_length=cfg.context_length,
            num_heads=cfg.num_heads,
            dropout=cfg.dropout_rate,
            qkv_bias=cfg.qkv_bias,
        )
        self.ff = FeedForward(cfg)
        self.norm1 = LayerNorm(cfg.emb_dim)
        self.norm2 = LayerNorm(cfg.emb_dim)
        self.drop_shortcut = nn.Dropout(cfg.dropout_rate)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Preserve `(batch_size, num_tokens, emb_dim)` through both sublayers."""
        # x and shortcut: (batch_size, num_tokens, emb_dim)
        shortcut = x
        # norm1 preserves: (batch_size, num_tokens, emb_dim)
        x = self.norm1(x)
        # att preserves shape because d_in == d_out == emb_dim.
        x = self.att(x)
        # Dropout changes values during training, never tensor shape.
        x = self.drop_shortcut(x)
        # Both operands: (batch_size, num_tokens, emb_dim)
        x = x + shortcut

        # Start the feed-forward shortcut from the attention sublayer output.
        # x and shortcut: (batch_size, num_tokens, emb_dim)
        shortcut = x
        # norm2 preserves: (batch_size, num_tokens, emb_dim)
        x = self.norm2(x)
        # ff expands internally to 4 * emb_dim, then returns emb_dim.
        x = self.ff(x)
        x = self.drop_shortcut(x)
        # Final output: (batch_size, num_tokens, emb_dim)
        x = x + shortcut
        return x

# %% ../notebooks/04-implementing-a-gpt-model.ipynb #994536ec5481d855
class GPTModel(nn.Module):
    """Assemble the token embeddings, Transformer blocks, and output head."""

    def __init__(self, cfg: GPTConfig) -> None:
        """Initialize a GPT model from a validated architecture configuration."""
        super().__init__()
        # Token and position lookups both produce vectors of width emb_dim.
        self.tok_emb = nn.Embedding(cfg.vocab_size, cfg.emb_dim)
        self.pos_emb = nn.Embedding(cfg.context_length, cfg.emb_dim)
        self.drop_emb = nn.Dropout(cfg.dropout_rate)

        # Every block preserves (batch_size, num_tokens, emb_dim).
        self.trf_blocks = nn.Sequential(*[TransformerBlock(cfg) for _ in range(cfg.num_layers)])

        self.final_norm = LayerNorm(cfg.emb_dim)
        # Map each token representation to one score per vocabulary entry.
        self.out_head = nn.Linear(cfg.emb_dim, cfg.vocab_size, bias=False)

    def forward(self, in_idx: torch.Tensor) -> torch.Tensor:
        """Map token IDs to next-token logits at every sequence position."""
        # in_idx: (batch_size, num_tokens)
        num_tokens = in_idx.shape[1]

        # tok_embeds: (batch_size, num_tokens, emb_dim)
        tok_embeds = self.tok_emb(in_idx)
        # positions: (num_tokens,)
        positions = torch.arange(num_tokens, device=in_idx.device)
        # pos_embeds: (num_tokens, emb_dim), broadcast across the batch
        pos_embeds = self.pos_emb(positions)

        # x: (batch_size, num_tokens, emb_dim)
        x = tok_embeds + pos_embeds
        # Embedding dropout preserves tensor shape.
        x = self.drop_emb(x)
        # Every Transformer block preserves the model dimension.
        x = self.trf_blocks(x)
        x = self.final_norm(x)
        # logits: (batch_size, num_tokens, vocab_size)
        logits = self.out_head(x)
        return logits
