# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/05-pretraining-on-unlabeled-data.ipynb.

# %% auto #0
__all__ = [
    "text_to_token_ids",
    "token_ids_to_text",
    "calc_loss_batch",
    "calc_loss_loader",
    "evaluate_model",
    "generate_and_print_sample",
    "train_model_simple",
    "plot_losses",
]

# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #nbdev-export-training-imports
import matplotlib.pyplot as plt
import tiktoken
import torch
from matplotlib.ticker import MaxNLocator
from torch.utils.data import DataLoader

from .generation import generate_text_simple
from .model import GPTModel


# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #751edc6f4e58ae32
def text_to_token_ids(
    text: str,
    tokenizer: tiktoken.Encoding,
) -> torch.Tensor:
    """Encode one text string as a batch containing one token-ID sequence.

    Args:
        text: Text to encode into GPT-2 token IDs.
        tokenizer: Tokenizer that maps text to token IDs.

    Returns:
        Token IDs shaped `(batch_size=1, num_tokens)`.
    """
    # encoded contains num_tokens integer token IDs.
    encoded = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
    # (num_tokens,) -> (batch_size=1, num_tokens)
    encoded_tensor = torch.tensor(encoded).unsqueeze(0)
    return encoded_tensor


def token_ids_to_text(
    token_ids: torch.Tensor,
    tokenizer: tiktoken.Encoding,
) -> str:
    """Decode a batch containing one token-ID sequence back into text.

    Args:
        token_ids: Token IDs shaped `(batch_size=1, num_tokens)`.
        tokenizer: Tokenizer that maps token IDs back to text.

    Returns:
        Decoded text for the single sequence in the batch.
    """
    # Remove the size-one batch dimension: (1, num_tokens) -> (num_tokens,).
    flat = token_ids.squeeze(0)
    return tokenizer.decode(flat.tolist())


# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #8202adfd763cef0e
def calc_loss_batch(
    input_batch: torch.Tensor,
    target_batch: torch.Tensor,
    model: GPTModel,
    device: torch.device,
) -> torch.Tensor:
    """Calculate cross-entropy for one batch on the selected device.

    Args:
        input_batch: Input token IDs shaped `(batch_size, num_tokens)`.
        target_batch: Target token IDs shaped `(batch_size, num_tokens)`.
        model: GPT model that maps input token IDs to vocabulary logits.
        device: CPU or CUDA device used for the tensors and model.

    Returns:
        Scalar cross-entropy loss with shape `()`.
    """
    # Device transfer preserves: (batch_size, num_tokens)
    input_batch = input_batch.to(device)
    target_batch = target_batch.to(device)
    # logits: (batch_size, num_tokens, vocab_size)
    logits = model(input_batch)
    # Flatten to (batch_size * num_tokens, vocab_size) and
    # (batch_size * num_tokens,) for cross-entropy.
    loss = torch.nn.functional.cross_entropy(
        logits.flatten(0, 1),
        target_batch.flatten(),
    )
    return loss


# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #91cb51929fc29628
def calc_loss_loader(
    data_loader: DataLoader[tuple[torch.Tensor, torch.Tensor]],
    model: GPTModel,
    device: torch.device,
    num_batches: int | None = None,
) -> float:
    """Average cross-entropy across batches from one data loader.

    Args:
        data_loader: Loader yielding input and target token-ID batches, each
            shaped `(batch_size, num_tokens)`.
        model: GPT model used to calculate next-token logits.
        device: CPU or CUDA device used for the tensors and model.
        num_batches: Maximum number of batches to evaluate, or `None` to use
            the complete loader.

    Returns:
        Mean batch loss as a Python float, or `nan` for an empty loader.
    """
    # Accumulate scalar Python floats rather than retaining computation graphs.
    total_loss = 0.0
    if len(data_loader) == 0:
        return float("nan")
    if num_batches is None:
        num_batches = len(data_loader)
    else:
        # Never request more batches than the loader contains.
        num_batches = min(num_batches, len(data_loader))

    for i, (input_batch, target_batch) in enumerate(data_loader):
        # input_batch and target_batch: (batch_size, num_tokens)
        if i < num_batches:
            # loss: scalar tensor with shape ()
            loss = calc_loss_batch(input_batch, target_batch, model, device)
            total_loss += loss.item()
        else:
            break
    return total_loss / num_batches


# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #dfc3ff3239b3fe85
def evaluate_model(
    model: GPTModel,
    train_loader: DataLoader[tuple[torch.Tensor, torch.Tensor]],
    val_loader: DataLoader[tuple[torch.Tensor, torch.Tensor]],
    device: torch.device,
    eval_iter: int,
) -> tuple[float, float]:
    """Evaluate mean training and validation loss without updating parameters.

    Args:
        model: GPT model whose loss is being measured.
        train_loader: Loader yielding training input and target batches.
        val_loader: Loader yielding validation input and target batches.
        device: CPU or CUDA device shared by the model and each batch.
        eval_iter: Maximum number of batches evaluated from each loader.

    Returns:
        Mean training loss and mean validation loss as Python floats.
    """
    # Disable dropout so repeated evaluation uses deterministic model behavior.
    model.eval()
    with torch.no_grad():
        # Each loader creates a fresh iterator for this evaluation call.
        train_loss = calc_loss_loader(
            train_loader,
            model,
            device,
            num_batches=eval_iter,
        )
        val_loss = calc_loss_loader(
            val_loader,
            model,
            device,
            num_batches=eval_iter,
        )
    # Restore training behavior for the optimization loop.
    model.train()
    return train_loss, val_loss


# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #feca99eff4282b3d
def generate_and_print_sample(
    model: GPTModel,
    tokenizer: tiktoken.Encoding,
    device: torch.device,
    start_context: str,
) -> None:
    """Generate and print one text sample without updating model parameters.

    Args:
        model: GPT model used for greedy token generation.
        tokenizer: Tokenizer used to encode and decode the sample.
        device: CPU or CUDA device shared by the model and token IDs.
        start_context: Prompt text that begins the generated sample.

    Returns:
        None.
    """
    model.eval()
    # The position-embedding table has one row per supported token position.
    context_size = model.pos_emb.weight.shape[0]
    # encoded: (batch_size=1, num_tokens)
    encoded = text_to_token_ids(start_context, tokenizer).to(device)
    with torch.no_grad():
        # token_ids: (batch_size=1, num_tokens + max_new_tokens=50)
        token_ids = generate_text_simple(
            model=model,
            idx=encoded,
            max_new_tokens=50,
            context_size=context_size,
        )
    decoded_text = token_ids_to_text(token_ids, tokenizer)
    # Keep the sample on one output line for readable training logs.
    print(decoded_text.replace("\n", " "))
    model.train()


# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #9a14823654a4db0
def train_model_simple(
    model: GPTModel,
    train_loader: DataLoader[tuple[torch.Tensor, torch.Tensor]],
    val_loader: DataLoader[tuple[torch.Tensor, torch.Tensor]],
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    num_epochs: int,
    eval_freq: int,
    eval_iter: int,
    start_context: str,
    tokenizer: tiktoken.Encoding,
) -> tuple[list[float], list[float], list[int]]:
    """Train a GPT model and periodically record loss and generated text.

    Args:
        model: GPT model whose parameters are updated.
        train_loader: Loader yielding training input and target batches.
        val_loader: Loader yielding validation input and target batches.
        optimizer: Optimizer that updates model parameters from gradients.
        device: CPU or CUDA device shared by the model and each batch.
        num_epochs: Number of complete passes through the training loader.
        eval_freq: Number of optimizer steps between loss evaluations.
        eval_iter: Maximum number of batches used for each evaluation.
        start_context: Prompt used for the sample generated after each epoch.
        tokenizer: Tokenizer used to encode and decode generated samples.

    Returns:
        Training losses, validation losses, and cumulative token counts
        recorded at each evaluation step.
    """
    train_losses: list[float] = []
    val_losses: list[float] = []
    track_tokens_seen: list[int] = []
    tokens_seen, global_step = 0, -1

    for epoch in range(num_epochs):
        model.train()
        # Iterating over train_loader starts a fresh, shuffled dataset pass.
        for input_batch, target_batch in train_loader:
            # input_batch and target_batch: (batch_size, num_tokens)
            optimizer.zero_grad()
            # loss: scalar tensor with shape ()
            loss = calc_loss_batch(input_batch, target_batch, model, device)
            # Populate gradients for every trainable model parameter.
            loss.backward()
            optimizer.step()
            # numel() equals batch_size * num_tokens for this input batch.
            tokens_seen += input_batch.numel()
            global_step += 1

            if global_step % eval_freq == 0:
                train_loss, val_loss = evaluate_model(
                    model,
                    train_loader,
                    val_loader,
                    device,
                    eval_iter,
                )
                train_losses.append(train_loss)
                val_losses.append(val_loss)
                track_tokens_seen.append(tokens_seen)
                print(
                    f"Ep {epoch + 1} (Step {global_step:06d}): "
                    f"Train loss {train_loss:.3f}, "
                    f"Val loss {val_loss:.3f}"
                )

        generate_and_print_sample(model, tokenizer, device, start_context)
    return train_losses, val_losses, track_tokens_seen


# %% ../notebooks/05-pretraining-on-unlabeled-data.ipynb #35c75922e6aa88d3
def plot_losses(
    epochs_seen: torch.Tensor,
    tokens_seen: list[int],
    train_losses: list[float],
    val_losses: list[float],
) -> None:
    """Plot training and validation loss against epochs and tokens seen.

    Args:
        epochs_seen: Epoch coordinates shaped `(num_evaluations,)`.
        tokens_seen: Cumulative token counts at each evaluation step.
        train_losses: Mean training losses at each evaluation step.
        val_losses: Mean validation losses at each evaluation step.

    Returns:
        None.
    """
    # All four inputs contain num_evaluations aligned values.
    fig, ax1 = plt.subplots(figsize=(5, 3))
    ax1.plot(epochs_seen, train_losses, label="Training loss")
    ax1.plot(
        epochs_seen,
        val_losses,
        linestyle="-.",
        label="Validation loss",
    )
    ax1.set_xlabel("Epochs")
    ax1.set_ylabel("Loss")
    ax1.legend(loc="upper right")
    # Epoch labels represent whole passes through the training loader.
    ax1.xaxis.set_major_locator(MaxNLocator(integer=True))

    # Add a second x-axis showing cumulative token positions processed.
    ax2 = ax1.twiny()
    # The invisible curve aligns the top axis with the loss measurements.
    ax2.plot(tokens_seen, train_losses, alpha=0)
    ax2.set_xlabel("Tokens seen")
    fig.tight_layout()
    plt.show()
